### ISSUE TITLE
incorrect ldrsh/pc relative lifting (from a support email, re-posted with permission)

### ISSUE THREAD

**Issue by psifertex** [Vector35/arch-armv7#51] opened 2021-06-24 20:38 UTC
I encountered a problem on the lifting of the ldrsh instruction on
thumb2/arm thumb2 decoding when using it relative to the program counter.
As I don't have a wide knowledge about all types of ARM devices I'm not
completely certain that this is wrong behavior,
but qemu executes it as assumed (and not like Binary Ninja displays) and
in IDA the same data is referenced as well.

I have tried the latest stable (2.4.2846 Personal) and dev (2.4.2875-dev
Personal) release and the problem occurs on both, I also found no issue
on the tracker related to this (I may have overlooked it though).

I've appended a screenshot of the assumed wrong behavior in Binary
Ninja, the assumed correct behavior in IDA and my binary this appears in.
![IDA_Correct](https://user-images.githubusercontent.com/140215/123329184-86a0b380-d50a-11eb-8271-6e2896fe50c5.png)
![BinaryNinja_Wrong](https://user-images.githubusercontent.com/140215/123329188-86a0b380-d50a-11eb-939c-7e9fe2e0cba7.png)
[bug.zip](https://github.com/Vector35/arch-armv7/files/6712017/bug.zip)

**Comment by lwerdna** [comment] 2022-07-08 19:44
Give our build machines a couple hours then check on dev update channel:

![fix](https://user-images.githubusercontent.com/474191/178059717-44c1f937-b1b8-4280-b36c-c18896f408c9.png)

**Comment by lwerdna** [comment] 2022-07-09 13:31
I verified the issue is resolved in 3.1.3558-dev.

**Closed by lwerdna** 2022-07-09 13:31 UTC
Labels: bug
