### ISSUE TITLE
Add an intrinsic function for pseudo C for `msr basepri, r3`

### ISSUE THREAD

**Issue by XVilka** [Vector35/arch-armv7#69] opened 2022-07-29 10:26 UTC
Binary Ninja Version: 3.1.3581-dev Personal, 67158f4e
Platform: macOS 12.3

It is a common instruction in all kinds of the ARM M-profile code
```
83f31188   msr     basepri, r3
```
in Pseudo C shown as
```c
        /* unimplemented  {msr basepri, r3} */;
```
It could be `void __set_BASEPRI (uint32_t basePri)` like in CMSIS: https://www.keil.com/pack/doc/cmsis/Core/html/group__Core__Register__gr.html

**Comment by fuzyll** [comment] 2022-08-01 17:11
I have transferred this issue to our ARMv7 repo because the fix for this needs to be implemented here. This is not HLIL-related, it's a lower level lifting issue.

**Comment by lwerdna** [comment] 2022-08-03 14:44
[test.zip](https://github.com/Vector35/arch-armv7/files/9252474/test.zip)

**Comment by lwerdna** [comment] 2022-08-06 05:08
Hopefully [fixed](https://github.com/Vector35/arch-armv7/commit/4bb371b320bfc36c62c7e2af044a873797e688da)!

![screenshot](https://user-images.githubusercontent.com/474191/183234919-755ef842-4a07-434c-93e0-871514af2a68.png)

Please wait a few hours for tests to pass and build machines to finish and it should be on dev update channel.

There were more changes necessary than I thought, so hopefully there's no regression.

**Comment by lwerdna** [comment] 2022-08-08 15:06
I'm treating this as resolved. Please reopen if incorrect.

**Closed by lwerdna** 2022-08-08 15:06 UTC

**Comment by XVilka** [comment] 2022-08-23 08:42
@lwerdna one more thing `msr psp, r0` produces `__msr(r0_X)` but `mrs r0, psp` says `unimplemented`. Probably a few lines change.
